export enum InputID {
  DefaultInput,
  LanguageSelect,
  isDarkModeCheckbox,
  isSoundsCheckbox,
  Premise,
  FirstMetaVariable,
  SecondMetaVariable,
  ThirdMetaVariable,
  Preview,
  NewVariable,
  OldVariable,
  Shortcut,
  Comment,
  FileName,
}
